import type { ModelManifest } from '../../types'

/**
 * Aishi（PixVerse）视频系列 manifest（provider: dashscope，category: video）。
 *
 * 走 video-synthesis 异步任务端点（provider_async），按视频秒数计费，1080P 单价
 * 高于 720P。本文件覆盖三种生成模式：
 *  - aishi-text-to-video：纯文生视频（mediaMode: none）
 *  - aishi-image-to-video：图生视频（pixverse-c1-it2v，单张输入图，mediaMode: single）
 *  - aishi-first-last-frame-video：首尾帧生视频（pixverse-c1-kf2v，两张图，mediaMode: multi）
 */

export const aishiT2V: ModelManifest = {
  id: 'aishi-text-to-video',
  provider: 'dashscope',
  providerModel: 'pixverse/pixverse-c1-t2v',
  displayName: 'Aishi (PixVerse) Text to Video',
  description: '爱诗 (PixVerse) 文生视频，创意视频生成',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'size',
      label: '视频尺寸',
      type: 'select',
      defaultValue: '1280*720',
      options: [
        ...[
          '640*360', '640*480', '640*640', '480*640', '360*640', '640*432', '432*640', '640*288',
          '1024*576', '1024*768', '1024*1024', '768*1024', '576*1024', '1024*688', '688*1024', '1024*448',
          '1280*720', '1108*832', '960*960', '832*1108', '720*1280', '1200*800', '800*1200', '1280*560',
          '1920*1080', '1664*1248', '1440*1440', '1248*1664', '1080*1920', '1776*1184', '1184*1776', '1920*832',
        ].map(value => ({ label: value.replace('*', '×'), value })),
      ],
    },
    { name: 'audio', label: '生成音频', type: 'boolean', defaultValue: false },
    { name: 'watermark', label: '水印', type: 'boolean', defaultValue: false },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      size: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3',
        conditions: { audio: false },
      },
      {
        id: 'cn-beijing-720p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.39',
        conditions: { audio: true },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}

export const aishiI2V: ModelManifest = {
  id: 'aishi-image-to-video',
  provider: 'dashscope',
  providerModel: 'pixverse/pixverse-c1-it2v',
  displayName: 'Aishi (PixVerse) Image to Video',
  description: '爱诗 (PixVerse) 图生视频，以输入图像为起点生成视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'seed'],
  parameters: [
    {
      name: 'image',
      label: '输入图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '作为视频基础的图像URL，推荐1张（多张时模型默认采用最后一张）',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '360P', value: '360P' },
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'single',
    bindings: {
      image: { target: 'input.media', mediaType: 'image_url' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-360p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.24',
        conditions: { resolution: '360P', audio: true },
      },
      {
        id: 'cn-beijing-360p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.18',
        conditions: { resolution: '360P', audio: false },
      },
      {
        id: 'cn-beijing-540p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3',
        conditions: { resolution: '540P', audio: true },
      },
      {
        id: 'cn-beijing-540p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.24',
        conditions: { resolution: '540P', audio: false },
      },
      {
        id: 'cn-beijing-720p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.39',
        conditions: { resolution: '720P', audio: true },
      },
      {
        id: 'cn-beijing-720p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3',
        conditions: { resolution: '720P', audio: false },
      },
      {
        id: 'cn-beijing-1080p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.71',
        conditions: { resolution: '1080P', audio: true },
      },
      {
        id: 'cn-beijing-1080p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.56',
        conditions: { resolution: '1080P', audio: false },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}

export const aishiFirstLastFrame: ModelManifest = {
  id: 'aishi-first-last-frame-video',
  provider: 'dashscope',
  providerModel: 'pixverse/pixverse-c1-kf2v',
  displayName: 'Aishi (PixVerse) First-Last Frame to Video',
  description: '爱诗 (PixVerse) 首尾帧视频生成，连接首尾画面生成视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'seed'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频起始帧图像URL',
    },
    {
      name: 'lastFrame',
      label: '尾帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频结束帧图像URL',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      maxLength: 5000,
      required: true,
      description: '描述首帧到尾帧之间的变化过程',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '360P', value: '360P' },
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'first_frame' },
      lastFrame: { target: 'input.media', mediaType: 'last_frame' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-360p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.24',
        conditions: { resolution: '360P', audio: true },
      },
      {
        id: 'cn-beijing-360p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.18',
        conditions: { resolution: '360P', audio: false },
      },
      {
        id: 'cn-beijing-540p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3',
        conditions: { resolution: '540P', audio: true },
      },
      {
        id: 'cn-beijing-540p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.24',
        conditions: { resolution: '540P', audio: false },
      },
      {
        id: 'cn-beijing-720p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.39',
        conditions: { resolution: '720P', audio: true },
      },
      {
        id: 'cn-beijing-720p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3',
        conditions: { resolution: '720P', audio: false },
      },
      {
        id: 'cn-beijing-1080p-audio-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.71',
        conditions: { resolution: '1080P', audio: true },
      },
      {
        id: 'cn-beijing-1080p-silent-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.56',
        conditions: { resolution: '1080P', audio: false },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}
