import type { ModelManifest } from '../../types'

/**
 * 可灵（Keling）视频系列 manifest（provider: dashscope，category: video）。
 *
 * 走 video-synthesis 异步任务端点（provider_async），按视频秒数计费，pro 模式
 * （1080P）单价高于 std 模式（720P）。本文件覆盖四种生成模式：
 *  - keling-text-to-video：文生视频（kling-v3-video-generation，mediaMode: none）
 *  - keling-image-to-video：图生视频（kling-v3-omni，单张首帧图，mediaMode: single）
 *  - keling-first-last-frame-video：首尾帧生视频（kling-v3-omni，mediaMode: multi）
 *  - keling-reference-video：参考图 + 特征视频生成（kling-v3-omni，references+featureVideo，
 *    mediaMode: multi；prompt 中用 <<<image_n>>> / <<<video_n>>> 指代素材）
 *  - keling-video-edit：视频编辑（kling-v3-omni，video 为 base + references 为 refer，
 *    mediaMode: multi，顺序敏感：base 必须排在 refer 之前）
 */

export const kelingT2V: ModelManifest = {
  id: 'keling-text-to-video',
  provider: 'dashscope',
  providerModel: 'kling/kling-v3-video-generation',
  displayName: 'Keling Text to Video',
  description: '可灵文生视频，画质与动作流畅度出众',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 2500,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'mode',
      label: '生成模式',
      type: 'select',
      defaultValue: 'pro',
      options: [
        { label: 'std（标准模式，720P）', value: 'std' },
        { label: 'pro（专业模式，1080P）', value: 'pro' },
      ],
    },
    {
      name: 'aspectRatio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"可灵AI"水印',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      mode: { target: 'parameters.field' },
      aspectRatio: { target: 'parameters.field', field: 'aspect_ratio' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    tiers: [
      { condition: {}, priceCents: 60 },
      { condition: { mode: 'pro' }, priceCents: 80 },
    ],
  },
  availability: { enabled: true, stage: 'beta' },
}

export const kelingI2V: ModelManifest = {
  id: 'keling-image-to-video',
  provider: 'dashscope',
  providerModel: 'kling/kling-v3-omni-video-generation',
  displayName: 'Keling Image to Video',
  description: '可灵图生视频，让静态图像动起来',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '作为视频起始帧的图像URL，有且仅有1张；输出宽高比以首帧为基准',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 2500,
      description: '描述期望生成的视频内容，支持中英文',
    },
    {
      name: 'mode',
      label: '生成模式',
      type: 'select',
      defaultValue: 'std',
      options: [
        { label: 'std（标准模式，720P）', value: 'std' },
        { label: 'pro（专业模式，1080P）', value: 'pro' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"可灵AI"水印',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'single',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'first_frame' },
      prompt: { target: 'input.prompt' },
      mode: { target: 'parameters.field' },
      duration: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    tiers: [
      { condition: {}, priceCents: 60 },
      { condition: { mode: 'pro' }, priceCents: 80 },
    ],
  },
  availability: { enabled: true, stage: 'beta' },
}

export const kelingFirstLastFrame: ModelManifest = {
  id: 'keling-first-last-frame-video',
  provider: 'dashscope',
  providerModel: 'kling/kling-v3-omni-video-generation',
  displayName: 'Keling First-Last Frame to Video',
  description: '可灵首尾帧生成，连接首尾画面生成完整视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频起始帧图像URL（media数组第一个 first_frame）',
    },
    {
      name: 'lastFrame',
      label: '尾帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频结束帧图像URL（media数组第二个 last_frame）',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 2500,
      description: '描述首帧到尾帧之间的变化过程',
    },
    {
      name: 'mode',
      label: '生成模式',
      type: 'select',
      defaultValue: 'std',
      options: [
        { label: 'std（标准模式，720P）', value: 'std' },
        { label: 'pro（专业模式，1080P）', value: 'pro' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"可灵AI"水印',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'first_frame' },
      lastFrame: { target: 'input.media', mediaType: 'last_frame' },
      prompt: { target: 'input.prompt' },
      mode: { target: 'parameters.field' },
      duration: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    tiers: [
      { condition: {}, priceCents: 60 },
      { condition: { mode: 'pro' }, priceCents: 80 },
    ],
  },
  availability: { enabled: true, stage: 'beta' },
}

export const kelingReferenceVideo: ModelManifest = {
  id: 'keling-reference-video',
  provider: 'dashscope',
  providerModel: 'kling/kling-v3-omni-video-generation',
  displayName: 'Keling Reference to Video',
  description: '可灵参考生视频，参考角色与图像生成一致的视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'video_input', 'multi_reference'],
  parameters: [
    {
      name: 'references',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: false,
      minItems: 1,
      maxItems: 7,
      description: '参考图像URL（type=refer），prompt中用<<<image_1>>>、<<<image_2>>>指代',
    },
    {
      name: 'featureVideo',
      label: '特征参考视频',
      type: 'media',
      mediaKind: 'video',
      required: false,
      maxItems: 1,
      description: '参考视频URL（type=feature），提供主体与音色参考',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 2500,
      description: '描述生成内容，可用<<<image_n>>>、<<<video_n>>>指代参考素材',
    },
    {
      name: 'mode',
      label: '生成模式',
      type: 'select',
      defaultValue: 'std',
      options: [
        { label: 'std（标准模式，720P）', value: 'std' },
        { label: 'pro（专业模式，1080P）', value: 'pro' },
      ],
    },
    {
      name: 'aspectRatio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 10,
      step: 1,
      description: '生成视频的时长，单位秒（含参考视频时取值[3,10]）',
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频（含参考视频时只能为false）',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"可灵AI"水印',
    },
  ],
  mediaGroups: [
    { parameters: ['references', 'featureVideo'], minItems: 1 },
    {
      parameters: ['references', 'featureVideo'],
      maxItems: 5,
      when: { field: 'featureVideo', present: true },
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    referenceFormat: 'angle-bracket',
    bindings: {
      references: { target: 'input.media', mediaType: 'refer' },
      featureVideo: { target: 'input.media', mediaType: 'feature' },
      prompt: { target: 'input.prompt' },
      mode: { target: 'parameters.field' },
      aspectRatio: { target: 'parameters.field', field: 'aspect_ratio' },
      duration: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    tiers: [
      { condition: {}, priceCents: 90 },
      { condition: { mode: 'pro' }, priceCents: 120 },
    ],
  },
  availability: { enabled: true, stage: 'beta' },
}

export const kelingVideoEdit: ModelManifest = {
  id: 'keling-video-edit',
  provider: 'dashscope',
  providerModel: 'kling/kling-v3-omni-video-generation',
  displayName: 'Keling Video Edit',
  description: '可灵视频编辑，对输入视频进行重绘与局部修改',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'video_input', 'image_input'],
  parameters: [
    {
      name: 'video',
      label: '待编辑视频',
      type: 'media',
      mediaKind: 'video',
      required: true,
      description: '待编辑的视频URL（type=base），有且仅有1个（mp4/mov，3~10s）',
    },
    {
      name: 'references',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: false,
      maxItems: 4,
      description: '参考图像URL（type=refer），用于局部替换等编辑指令',
    },
    {
      name: 'prompt',
      label: '编辑指令',
      type: 'text',
      required: false,
      maxLength: 2500,
      description: '描述对视频的编辑意图',
    },
    {
      name: 'mode',
      label: '生成模式',
      type: 'select',
      defaultValue: 'std',
      options: [
        { label: 'std（标准模式，720P）', value: 'std' },
        { label: 'pro（专业模式，1080P）', value: 'pro' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 10,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"可灵AI"水印',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      // media 数组顺序敏感：base（待编辑视频）必须排在 refer（参考图）之前
      video: { target: 'input.media', mediaType: 'base' },
      references: { target: 'input.media', mediaType: 'refer' },
      prompt: { target: 'input.prompt' },
      mode: { target: 'parameters.field' },
      duration: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    tiers: [
      { condition: {}, priceCents: 90 },
      { condition: { mode: 'pro' }, priceCents: 120 },
    ],
  },
  availability: { enabled: true, stage: 'beta' },
}
