import type { ModelManifest } from '../../types'

export const qwenOmniScreenplayFlash: ModelManifest = {
  id: 'qwen-omni-screenplay-flash',
  provider: 'dashscope',
  providerModel: 'qwen3.5-omni-flash',
  displayName: '视频生成剧本（快速版）',
  description: '从视频中快速提取关键信息生成剧本，速度优先',
  category: 'video',
  taskMode: 'stream',
  capabilities: ['video_input', 'streaming'],
  parameters: [
    {
      name: 'videoUrl',
      label: '视频 URL',
      type: 'media',
      mediaKind: 'video',
      required: true,
      description: '从资产库选择、上传视频，或粘贴公开 URL（MP4/AVI/MKV/MOV/FLV 等格式）',
    },
    {
      name: 'language',
      label: '输出语言',
      type: 'select',
      defaultValue: 'zh',
      options: [
        { label: '中文', value: 'zh' },
        { label: '英文', value: 'en' },
        { label: '中英双语', value: 'zh_en' },
      ],
    },
    {
      name: 'detailLevel',
      label: '精细度',
      type: 'select',
      defaultValue: 'standard',
      options: [
        { label: '标准（场景+对白）', value: 'standard' },
        { label: '精细（含镜头/音效描述）', value: 'detailed' },
      ],
    },
    {
      name: 'estimatedDuration',
      label: '预估视频时长(秒)',
      type: 'number',
      defaultValue: 60,
      min: 1,
      description: '仅用于费用预估，不影响结果',
    },
    {
      name: 'mode',
      label: '计费模式（内部）',
      type: 'select',
      options: [
        { label: '图像/视频输入', value: 'text-image-video-input' },
        { label: '音频输入', value: 'audio-input' },
        { label: '多模态文本输出', value: 'multimodal-input-text-output' },
        { label: '音频输出', value: 'audio-output' },
      ],
      visibleWhen: { field: 'videoUrl', equals: 'internal:never-user-visible' },
      description: '内部计费模式标记，由 usage token 桶映射到 rates 的 conditions.mode，不对用户展示',
    },
  ],
  request: {
    kind: 'dashscope-chat',
    endpoint: '/compatible-mode/v1/chat/completions',
    promptParam: 'prompt',
    stream: true,
    bindings: {
      videoUrl: { target: 'ui.only' },
      language: { target: 'ui.only' },
      detailLevel: { target: 'ui.only' },
      estimatedDuration: { target: 'ui.only' },
    },
  },
  output: { kind: 'text', path: 'output.text' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'estimatedDuration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-visual-text-input-token',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'input',
        unit: 'token',
        unitSize: 1000000,
        unitPrice: '2.2',
        conditions: { mode: 'text-image-video-input' },
      },
      {
        id: 'cn-beijing-audio-input-token',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'input',
        unit: 'token',
        unitSize: 1000000,
        unitPrice: '18',
        conditions: { mode: 'audio-input' },
      },
      {
        id: 'cn-beijing-multimodal-text-output-token',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'token',
        unitSize: 1000000,
        unitPrice: '13.3',
        conditions: { mode: 'multimodal-input-text-output' },
      },
      {
        id: 'cn-beijing-audio-output-token',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'token',
        unitSize: 1000000,
        unitPrice: '72',
        conditions: { mode: 'audio-output' },
      },
    ],
  },
  transport: {
    mode: 'stream',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/chat/completions',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
      ],
    },
    stream: {
      contentTypes: ['text/event-stream'],
      framing: 'sse',
      headers: [],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}
