import type { ModelManifest } from '../../types'

/**
 * 万相 2.7 视频系列 manifest（provider: dashscope，category: video）。
 *
 * 走 video-synthesis 异步任务端点（provider_async），按视频秒数计费，1080P 单价
 * 高于 720P。本系列的特殊点：negative_prompt 与 audio_url 不是放在 parameters 下，
 * 而是绑到 input.field（与 DashScope 该模型的请求结构一致）。覆盖四种生成模式：
 *  - wanx-2.7-text-to-video：文生视频（wan2.7-t2v，mediaMode: none）
 *  - wanx-2.7-image-to-video：图生视频（wan2.7-i2v，首帧图 + 可选驱动音频，
 *    mediaMode: multi）
 *  - wanx-2.7-reference-video：参考图/视频生视频（wan2.7-r2v，references +
 *    referenceVideos，mediaMode: multi）
 *  - wanx-2.7-video-edit：视频编辑（wan2.7-videoedit，video + referenceImages，
 *    mediaMode: multi，顺序敏感：video 必须排在 reference_image 之前；
 *    duration 仅用于费用预估，模型实际沿用输入视频时长）
 */

export const wanx27T2V: ModelManifest = {
  id: 'wanx-2.7-text-to-video',
  provider: 'dashscope',
  providerModel: 'wan2.7-t2v',
  displayName: 'Wanxiang 2.7 Text to Video',
  description: '通义万相 2.7 文生视频，支持生成带配音与背景音的视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed', 'audio_input'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点，支持时间戳分镜描述',
    },
    {
      name: 'negativePrompt',
      label: '反向提示词',
      type: 'text',
      required: false,
      maxLength: 500,
      description: '描述不希望在视频画面中看到的内容',
    },
    {
      name: 'audioUrl',
      label: '音频文件URL',
      type: 'text',
      required: false,
      description: '支持传入自定义音频，格式：wav/mp3，时长2-30s',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 2,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'ratio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ],
    },
    {
      name: 'promptExtend',
      label: '智能改写',
      type: 'boolean',
      defaultValue: true,
      description: '开启prompt智能改写，对短prompt效果提升明显',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      negativePrompt: { target: 'input.field', field: 'negative_prompt' },
      audioUrl: { target: 'input.field', field: 'audio_url' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      ratio: { target: 'parameters.field' },
      promptExtend: { target: 'parameters.field', field: 'prompt_extend' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.6',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'stable' },
}

export const wanx27I2V: ModelManifest = {
  id: 'wanx-2.7-image-to-video',
  provider: 'dashscope',
  providerModel: 'wan2.7-i2v-2026-04-25',
  displayName: 'Wanxiang 2.7 Image to Video',
  description: '通义万相 2.7 图生视频，以输入图像为起点生成带配音视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'audio_input', 'negative_prompt', 'seed'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '作为视频起始帧的图像URL，有且仅有1张；输出宽高比尽量接近首帧',
    },
    {
      name: 'drivingAudio',
      label: '驱动音频',
      type: 'media',
      mediaKind: 'audio',
      required: false,
      description: '驱动音频URL（wav/mp3，2~30s）；未传入时模型自动生成背景音乐或音效',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'negativePrompt',
      label: '反向提示词',
      type: 'text',
      required: false,
      maxLength: 500,
      description: '描述不希望在视频画面中看到的内容',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 2,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'promptExtend',
      label: '智能改写',
      type: 'boolean',
      defaultValue: true,
      description: '开启prompt智能改写，对短prompt效果提升明显',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'first_frame' },
      drivingAudio: { target: 'input.media', mediaType: 'driving_audio' },
      prompt: { target: 'input.prompt' },
      negativePrompt: { target: 'input.field', field: 'negative_prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      promptExtend: { target: 'parameters.field', field: 'prompt_extend' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.6',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'stable' },
}

export const wanx27R2V: ModelManifest = {
  id: 'wanx-2.7-reference-video',
  provider: 'dashscope',
  providerModel: 'wan2.7-r2v',
  displayName: 'Wanxiang 2.7 Reference to Video',
  description: '通义万相 2.7 参考生视频，多图/视频参考保持角色一致',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'video_input', 'multi_reference', 'negative_prompt', 'seed'],
  parameters: [
    {
      name: 'references',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: false,
      maxItems: 5,
      description: '参考图像URL（图1、图2…），与参考视频合计1~5个；prompt中用"图n"或"Image n"指代',
    },
    {
      name: 'referenceVideos',
      label: '参考视频',
      type: 'media',
      mediaKind: 'video',
      required: false,
      maxItems: 5,
      description: '参考视频URL（视频1、视频2…），与参考图像合计1~5个；用于角色与音色参考',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素，用"图n/视频n"指代参考素材',
    },
    {
      name: 'negativePrompt',
      label: '反向提示词',
      type: 'text',
      required: false,
      maxLength: 500,
      description: '描述不希望在视频画面中看到的内容',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'ratio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 2,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒；含参考视频时取值[2,10]',
      conditional: { max: 10, when: { field: 'referenceVideos', present: true } },
    },
    {
      name: 'promptExtend',
      label: '智能改写',
      type: 'boolean',
      defaultValue: true,
      description: '开启prompt智能改写，对短prompt效果提升明显',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
    rules: [
    {
      kind: 'media-group',
      fields: ['references', 'referenceVideos'],
      minItems: 1,
      maxItems: 5,
      code: 'TOO_MANY_MEDIA',
      message: { 'zh-CN': '参考图片与参考视频合计需为 1~5 个', 'en-US': 'References and reference videos together must total 1 to 5' },
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    referenceFormat: 'chinese',
    bindings: {
      references: { target: 'input.media', mediaType: 'reference_image' },
      referenceVideos: { target: 'input.media', mediaType: 'reference_video' },
      prompt: { target: 'input.prompt' },
      negativePrompt: { target: 'input.field', field: 'negative_prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      ratio: { target: 'parameters.field' },
      promptExtend: { target: 'parameters.field', field: 'prompt_extend' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.6',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'stable' },
}

export const wanx27VideoEdit: ModelManifest = {
  id: 'wanx-2.7-video-edit',
  provider: 'dashscope',
  providerModel: 'wan2.7-videoedit',
  displayName: 'Wanxiang 2.7 Video Edit',
  description: '通义万相 2.7 视频编辑，对已有视频进行局部修改与重绘',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'video_input', 'image_input', 'negative_prompt', 'seed'],
  parameters: [
    {
      name: 'video',
      label: '待编辑视频',
      type: 'media',
      mediaKind: 'video',
      required: true,
      description: '待编辑的视频URL，有且仅有1个（mp4/mov，2~10s）',
    },
    {
      name: 'referenceImages',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: false,
      maxItems: 4,
      description: '0~4张参考图像URL，用于局部替换等编辑指令',
    },
    {
      name: 'prompt',
      label: '编辑指令',
      type: 'text',
      required: false,
      maxLength: 5000,
      description: '描述对视频的编辑意图，如风格转换、局部替换等',
    },
    {
      name: 'negativePrompt',
      label: '反向提示词',
      type: 'text',
      required: false,
      maxLength: 500,
      description: '描述不希望在视频画面中出现的内容',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'ratio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
      ],
    },
    {
      name: 'duration',
      label: '预估时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 2,
      max: 10,
      step: 1,
      description: '预估输出视频时长，仅用于费用预估（默认0表示沿用输入视频时长，不截断）',
    },
    {
      name: 'audioSetting',
      label: '声音设置',
      type: 'select',
      defaultValue: 'auto',
      options: [
        { label: 'auto（模型智能判断）', value: 'auto' },
        { label: 'origin（保留原声）', value: 'origin' },
      ],
    },
    {
      name: 'promptExtend',
      label: '智能改写',
      type: 'boolean',
      defaultValue: true,
      description: '开启prompt智能改写',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      // 顺序敏感：video 必须在 reference_image 之前
      video: { target: 'input.media', mediaType: 'video' },
      referenceImages: { target: 'input.media', mediaType: 'reference_image' },
      prompt: { target: 'input.prompt' },
      negativePrompt: { target: 'input.field', field: 'negative_prompt' },
      resolution: { target: 'parameters.field' },
      ratio: { target: 'parameters.field' },
      audioSetting: { target: 'parameters.field', field: 'audio_setting' },
      promptExtend: { target: 'parameters.field', field: 'prompt_extend' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
      // duration 仅用于费用预估，不发送给 provider（默认0=沿用输入视频时长）
      duration: { target: 'ui.only' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.6',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'stable' },
}
