import type { ModelManifest } from '@bailian-studio/model-core'

/**
 * HappyHorse 视频系列 manifest（provider: dashscope，category: video）。
 *
 * 走 video-synthesis 异步任务端点（provider_async），按视频秒数计费，1080P 单价
 * 高于 720P。本文件覆盖四种生成模式：
 *  - happyhorse-text-to-video：文生视频（1.1-t2v，mediaMode: none）
 *  - happyhorse-image-to-video：图生视频（1.1-i2v，单张首帧图，mediaMode: single）
 *  - happyhorse-reference-video：多参考图生视频（1.1-r2v，1~9 张参考图，mediaMode: multi）
 *  - happyhorse-video-edit：视频编辑（1.0-video-edit，输入视频 + 0~5 张参考图，
 *    mediaMode: multi；duration 仅用于费用预估，模型实际输出跟随输入视频时长）
 */

export const happyhorseT2V: ModelManifest = {
  id: 'happyhorse-text-to-video',
  provider: 'dashscope',
  providerModel: 'happyhorse-1.1-t2v',
  displayName: 'HappyHorse Text to Video',
  description: '欢乐马文生视频，支持多种画幅与风格',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点，支持时间戳分镜描述',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '480P', value: '480P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'ratio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
        { label: '4:5', value: '4:5' },
        { label: '5:4', value: '5:4' },
        { label: '9:21', value: '9:21' },
        { label: '21:9', value: '21:9' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否在视频右下角添加"Happy Horse"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
    rules: [
    {
      kind: 'text-length',
      field: 'prompt',
      cjk: { max: 2500 },
      other: { max: 5000 },
      code: 'OUT_OF_RANGE',
      message: { 'zh-CN': 'prompt 最多包含 2500 个中文字符或 5000 个非中文字符', 'en-US': 'The prompt may contain at most 2500 Chinese characters or 5000 non-Chinese characters' },
    },
  ],
request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      ratio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-480p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.45',
        conditions: { resolution: '480P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1.2',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}

export const happyhorseI2V: ModelManifest = {
  id: 'happyhorse-image-to-video',
  provider: 'dashscope',
  providerModel: 'happyhorse-1.1-i2v',
  displayName: 'HappyHorse Image to Video',
  description: '欢乐马图生视频，以输入图像为起点生成视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'seed'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '作为视频起始帧的图像URL，有且仅有1张；输出宽高比跟随首帧',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 5000,
      description: '描述期望生成的视频内容，可选',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '480P', value: '480P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否在视频右下角添加"Happy Horse"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
    rules: [
    {
      kind: 'text-length',
      field: 'prompt',
      cjk: { max: 2500 },
      other: { max: 5000 },
      code: 'OUT_OF_RANGE',
      message: { 'zh-CN': 'prompt 最多包含 2500 个中文字符或 5000 个非中文字符', 'en-US': 'The prompt may contain at most 2500 Chinese characters or 5000 non-Chinese characters' },
    },
  ],
request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'single',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'first_frame' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-480p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.45',
        conditions: { resolution: '480P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1.2',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}

export const happyhorseR2V: ModelManifest = {
  id: 'happyhorse-reference-video',
  provider: 'dashscope',
  providerModel: 'happyhorse-1.1-r2v',
  displayName: 'HappyHorse Reference to Video',
  description: '欢乐马参考生视频，多参考图保持角色一致',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'multi_reference', 'seed'],
  parameters: [
    {
      name: 'references',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      minItems: 1,
      maxItems: 9,
      description: '1~9张参考图像URL；prompt中用[Image 1]、[Image 2]指代对应位置的图像',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素，可用[Image 1]/[Image 2]指代参考图中的角色',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '480P', value: '480P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'ratio',
      label: '宽高比',
      type: 'select',
      defaultValue: '16:9',
      options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
        { label: '4:3', value: '4:3' },
        { label: '3:4', value: '3:4' },
        { label: '4:5', value: '4:5' },
        { label: '5:4', value: '5:4' },
        { label: '9:21', value: '9:21' },
        { label: '21:9', value: '21:9' },
      ],
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '生成视频的时长，单位秒',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否在视频右下角添加"Happy Horse"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
    rules: [
    {
      kind: 'text-length',
      field: 'prompt',
      cjk: { max: 2500 },
      other: { max: 5000 },
      code: 'OUT_OF_RANGE',
      message: { 'zh-CN': 'prompt 最多包含 2500 个中文字符或 5000 个非中文字符', 'en-US': 'The prompt may contain at most 2500 Chinese characters or 5000 non-Chinese characters' },
    },
  ],
request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    referenceFormat: 'image-bracket',
    bindings: {
      references: { target: 'input.media', mediaType: 'reference_image' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      ratio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-480p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.45',
        conditions: { resolution: '480P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1.2',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}

export const happyhorseVideoEdit: ModelManifest = {
  id: 'happyhorse-video-edit',
  provider: 'dashscope',
  providerModel: 'happyhorse-1.0-video-edit',
  displayName: 'HappyHorse Video Edit',
  description: '欢乐马视频编辑，对视频局部进行修改与重绘',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'video_input', 'image_input', 'seed'],
  parameters: [
    {
      name: 'video',
      label: '待编辑视频',
      type: 'media',
      mediaKind: 'video',
      required: true,
      description: '待编辑的视频URL，有且仅有1个；输出时长3~15秒，超过15秒自动截取前15秒',
    },
    {
      name: 'referenceImages',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: false,
      maxItems: 5,
      description: '0~5张参考图像URL，用于局部替换等编辑指令',
    },
    {
      name: 'prompt',
      label: '编辑指令',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述对视频的编辑意图，如风格转换、局部替换等',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '1080P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否在视频右下角添加"Happy Horse"水印',
    },
    {
      name: 'audioSetting',
      label: '声音设置',
      type: 'select',
      defaultValue: 'auto',
      options: [
        { label: 'auto（模型自行控制）', value: 'auto' },
        { label: 'origin（保留原声）', value: 'origin' },
      ],
    },
    {
      name: 'duration',
      label: '预估时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 3,
      max: 15,
      step: 1,
      description: '预估输出视频时长，仅用于费用预估（模型实际输出3~15秒，跟随输入视频）',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0,
      max: 2147483647,
      step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
    rules: [
    {
      kind: 'text-length',
      field: 'prompt',
      cjk: { max: 2500 },
      other: { max: 5000 },
      code: 'OUT_OF_RANGE',
      message: { 'zh-CN': 'prompt 最多包含 2500 个中文字符或 5000 个非中文字符', 'en-US': 'The prompt may contain at most 2500 Chinese characters or 5000 non-Chinese characters' },
    },
  ],
request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      video: { target: 'input.media', mediaType: 'video' },
      referenceImages: { target: 'input.media', mediaType: 'reference_image' },
      prompt: { target: 'input.prompt' },
      resolution: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      audioSetting: { target: 'parameters.field', field: 'audio_setting' },
      seed: { target: 'parameters.field' },
      // duration 仅用于费用预估，不发送给 provider（视频编辑模型不接受 duration 参数，
      // 实际输出 3~15 秒，跟随输入视频时长）
      duration: { target: 'ui.only' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-input-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'input-and-output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-input-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'input-and-output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '1.6',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: true, stage: 'beta' },
}
