import type { ModelManifest } from '@bailian-studio/model-core'

/**
 * Vidu 视频系列 manifest（provider: dashscope，category: video）。
 *
 * 走 video-synthesis 异步任务端点（provider_async），按视频秒数计费，价格随分辨率
 * 档位（540P/720P/1080P）阶梯上浮。本文件覆盖多个生成模式：
 *  - vidu-text-to-video-pro：Q3 Pro 文生视频，支持 1~16s、音频、自定义尺寸
 *  - vidu-text-to-video-turbo：Q3 Turbo 文生视频，速度更快、价格更低
 *  - vidu-text-to-video：Q2 标准版文生视频，仅支持 1~10s、无音频
 *  - vidu-image-to-video：图生视频（Q3 Pro img2video，mediaMode: single）
 *  - vidu-first-last-frame-video：首尾帧生视频（Q3 Pro start-end2video，
 *    mediaMode: multi，首尾帧总像素比值需在 0.8~1.25 之间）
 *  - vidu-reference-video：多参考图生视频（Q3 mix reference2video，1~7 张参考图，
 *    mediaMode: multi，prompt 中用 [Image 1]/[Image 2] 指代）
 */

export const viduT2VPro: ModelManifest = {
  id: 'vidu-text-to-video-pro',
  provider: 'dashscope',
  providerModel: 'vidu/viduq3-pro_text2video',
  displayName: 'Vidu Text to Video Pro',
  description: 'Vidu 专业版文生视频，画质与角色一致性更佳',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 16,
      step: 1,
      description: '生成视频的时长，专业版支持1-16秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'size',
      label: '分辨率尺寸',
      type: 'select',
      defaultValue: '1280*720',
      options: [
        { label: '16:9 (1280×720)', value: '1280*720' },
        { label: '9:16 (720×1280)', value: '720*1280' },
        { label: '1:1 (1024×1024)', value: '1024*1024' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频，专业版支持',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      size: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-540p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3125',
        conditions: { resolution: '540P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.78125',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}

export const viduT2VTurbo: ModelManifest = {
  id: 'vidu-text-to-video-turbo',
  provider: 'dashscope',
  providerModel: 'vidu/viduq3-turbo_text2video',
  displayName: 'Vidu Text to Video Turbo',
  description: 'Vidu 极速版文生视频，生成快、成本低',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 16,
      step: 1,
      description: '生成视频的时长，turbo版支持1-16秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频，turbo版支持',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-540p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.25',
        conditions: { resolution: '540P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.375',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.4375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}

export const viduT2V: ModelManifest = {
  id: 'vidu-text-to-video',
  provider: 'dashscope',
  providerModel: 'vidu/viduq2_text2video',
  displayName: 'Vidu Text to Video',
  description: 'Vidu 文生视频，将文字描述转化为视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'seed'],
  parameters: [
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 10,
      step: 1,
      description: '生成视频的时长，标准版支持1-10秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'none',
    bindings: {
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-540p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.1125',
        conditions: { resolution: '540P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.21875',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}

export const viduI2V: ModelManifest = {
  id: 'vidu-image-to-video',
  provider: 'dashscope',
  providerModel: 'vidu/viduq3-pro_img2video',
  displayName: 'Vidu Image to Video',
  description: 'Vidu 图生视频，以输入图像为起点生成视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'seed'],
  parameters: [
    {
      name: 'image',
      label: '输入图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '作为视频基础的图像URL，有且仅有1张；输出宽高比尽量接近输入图像',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: false,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素和视觉特点',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 16,
      step: 1,
      description: '生成视频的时长，专业版支持1-16秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频，专业版支持',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"内容由AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'single',
    bindings: {
      image: { target: 'input.media', mediaType: 'image' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-540p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3125',
        conditions: { resolution: '540P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.78125',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}

export const viduFirstLastFrame: ModelManifest = {
  id: 'vidu-first-last-frame-video',
  provider: 'dashscope',
  providerModel: 'vidu/viduq3-pro_start-end2video',
  displayName: 'Vidu First-Last Frame to Video',
  description: 'Vidu 首尾帧视频生成，给定首尾画面生成过渡视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'seed'],
  parameters: [
    {
      name: 'firstFrame',
      label: '首帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频起始帧图像URL（media数组第一个 image）',
    },
    {
      name: 'lastFrame',
      label: '尾帧图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      description: '视频结束帧图像URL（media数组第二个 image）；与首帧总像素比值需在0.8~1.25之间',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述首帧到尾帧之间的变化过程',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 16,
      step: 1,
      description: '生成视频的时长，专业版支持1-16秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '540P', value: '540P' },
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频，专业版支持',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"内容由AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    bindings: {
      firstFrame: { target: 'input.media', mediaType: 'image' },
      lastFrame: { target: 'input.media', mediaType: 'image' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-540p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.3125',
        conditions: { resolution: '540P' },
      },
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.78125',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}

export const viduR2V: ModelManifest = {
  id: 'vidu-reference-video',
  provider: 'dashscope',
  providerModel: 'vidu/viduq3-mix_reference2video',
  displayName: 'Vidu Reference to Video',
  description: 'Vidu 参考生视频，参考多张图像生成风格一致的视频',
  category: 'video',
  taskMode: 'provider_async',
  capabilities: ['text_prompt', 'image_input', 'multi_reference', 'seed'],
  parameters: [
    {
      name: 'references',
      label: '参考图像',
      type: 'media',
      mediaKind: 'image',
      required: true,
      minItems: 1,
      maxItems: 7,
      description: '1~7张参考图像URL；prompt中可用[Image 1]、[Image 2]指代对应位置的图像',
    },
    {
      name: 'prompt',
      label: '提示词',
      type: 'text',
      required: true,
      maxLength: 5000,
      description: '描述生成视频中期望包含的元素，可用[Image 1]/[Image 2]指代参考图中的角色',
    },
    {
      name: 'duration',
      label: '视频时长(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      max: 16,
      step: 1,
      description: '生成视频的时长，专业版支持1-16秒',
    },
    {
      name: 'resolution',
      label: '分辨率档位',
      type: 'select',
      defaultValue: '720P',
      options: [
        { label: '720P', value: '720P' },
        { label: '1080P', value: '1080P' },
      ],
    },
    {
      name: 'audio',
      label: '生成音频',
      type: 'boolean',
      defaultValue: false,
      description: '是否生成有声视频，专业版支持',
    },
    {
      name: 'watermark',
      label: '水印',
      type: 'boolean',
      defaultValue: false,
      description: '是否添加"内容由AI生成"水印',
    },
    {
      name: 'seed',
      label: '随机种子',
      type: 'number',
      required: false,
      min: 0, max: 2147483647, step: 1,
      description: '随机数种子，取值范围[0,2147483647]',
    },
  ],
  request: {
    kind: 'dashscope-video-task',
    endpoint: '/services/aigc/video-generation/video-synthesis',
    mediaMode: 'multi',
    referenceFormat: 'image-bracket',
    bindings: {
      references: { target: 'input.media', mediaType: 'image' },
      prompt: { target: 'input.prompt' },
      duration: { target: 'parameters.field' },
      resolution: { target: 'parameters.field' },
      audio: { target: 'parameters.field' },
      watermark: { target: 'parameters.field' },
      seed: { target: 'parameters.field' },
    },
  },
  output: { kind: 'video-url', path: 'output.video_url' },
  pricing: {
    unit: 'per_second',
    quantityKey: 'duration',
    currency: 'CNY',
    rates: [
      {
        id: 'cn-beijing-720p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.78125',
        conditions: { resolution: '720P' },
      },
      {
        id: 'cn-beijing-1080p-output-second',
        region: 'cn-beijing',
        serviceScope: 'china-mainland',
        chargeItem: 'output',
        unit: 'second',
        unitSize: 1,
        unitPrice: '0.9375',
        conditions: { resolution: '1080P' },
      },
    ],
  },
  transport: {
    mode: 'provider_async',
    submit: {
      method: 'POST',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
      modelFieldPath: '/model',
      headers: [
        { name: 'Authorization' },
        { name: 'Content-Type', value: 'application/json' },
        { name: 'X-DashScope-Async', value: 'enable' },
      ],
    },
    polling: {
      method: 'GET',
      endpointTemplate: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/api/v1/tasks/{taskId}',
      headers: [{ name: 'Authorization' }],
      taskIdPath: '/output/task_id',
      statusPath: '/output/task_status',
      succeededValues: ['SUCCEEDED'],
      failedValues: ['FAILED', 'CANCELED', 'UNKNOWN'],
    },
  },
  availability: { enabled: false, stage: 'beta', notActivated: '暂未开通' },
}
