import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { buildBailianContractReport } from './report-bailian-contract'

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..')
const outputPath = join(root, 'packages', 'bailian-adapter', 'src', 'generated', 'coverage-baseline.ts')
const pnpmWorkspacePath = join(root, 'pnpm-workspace.yaml')

function quoted(value: string): string {
  return JSON.stringify(value)
}

/** 从 pnpm-workspace.yaml 的 catalog 段提取指定包名对应的版本值。 */
export function extractPnpmCatalogVersion(yaml: string, packageName: string): string | undefined {
  const escaped = packageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const pattern = new RegExp(
    `^\\s*["']?${escaped}["']?\\s*:\\s*["']?([^"'\\s#]+)["']?\\s*$`,
    'm',
  )
  const match = pattern.exec(yaml)
  return match?.[1]
}

export function renderBailianCoverageBaseline(): string {
  const { actual } = buildBailianContractReport()
  if (actual.maintenance !== 'official-sync') {
    throw new Error(`refusing to generate an automatic baseline for maintenance lane ${actual.maintenance}`)
  }
  const coveredConsumerIds = [...actual.coveredConsumerIds]
  if (new Set(coveredConsumerIds).size !== coveredConsumerIds.length) {
    throw new Error('installed Bailian SDK returned duplicate covered consumer IDs')
  }
  for (const hash of [actual.catalogHash, actual.requirementsHash]) {
    if (!/^sha256:[0-9a-f]{64}$/.test(hash)) throw new Error(`invalid Bailian baseline hash ${hash}`)
  }
  return [
    '/**',
    ' * Generated by infra/scripts/sync-bailian-coverage-baseline.ts from the exact',
    ' * installed @puzzle-fuzzy/bailian-sdk. Do not edit these values by hand.',
    ' */',
    'export const BAILIAN_STUDIO_BAILIAN_COVERAGE_BASELINE = Object.freeze({',
    `  sdkVersion: ${quoted(actual.sdkVersion)},`,
    `  catalogRevision: ${quoted(actual.catalogRevision)},`,
    `  catalogHash: ${quoted(actual.catalogHash)},`,
    `  requirementsHash: ${quoted(actual.requirementsHash)},`,
    `  totalRequirements: ${actual.totalRequirements},`,
    `  coveredRequirements: ${actual.coveredRequirements},`,
    `  uncoveredRequirements: ${actual.legacyRequirements},`,
    '  coveredConsumerIds: Object.freeze([',
    ...coveredConsumerIds.map((consumerId) => `    ${quoted(consumerId)},`),
    '  ]),',
    '})',
    '',
  ].join('\n')
}

async function main(): Promise<void> {
  const pnpmWorkspaceYaml = await readFile(pnpmWorkspacePath, 'utf8')
  const installedVersion = buildBailianContractReport().actual.sdkVersion
  const pinnedVersion = extractPnpmCatalogVersion(pnpmWorkspaceYaml, '@puzzle-fuzzy/bailian-sdk')
  if (pinnedVersion !== installedVersion) {
    throw new Error(`pnpm-workspace.yaml catalog pins ${String(pinnedVersion)}, but the installed Bailian SDK is ${installedVersion}`)
  }

  const expected = renderBailianCoverageBaseline()
  if (globalThis.process.argv.includes('--write')) {
    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(outputPath, expected, 'utf8')
    console.log(`Recorded Bailian SDK ${installedVersion} coverage baseline from the installed package`)
    return
  }
  const current = await readFile(outputPath, 'utf8').catch(() => '')
  if (current !== expected) throw new Error('Bailian coverage baseline is stale; run pnpm run bailian:baseline:sync')
  console.log(`Checked Bailian SDK ${installedVersion} coverage baseline`)
}

if (import.meta.main) await main()
