/**
 * @bailian-studio/shared 的公共出口（barrel）。
 *
 * 作为 monorepo 依赖图的最底层叶子包，向 services / apps / 其他 packages 暴露
 * 共享工具：日志（logger）、指标（metrics）、运行时校验（validation）和统一错误类型
 * （errors）。按 package 边界规则，本包不得 import 任何其它 @bailian-studio/* 包。
 */

export { createLogger, resolveLogFormat, safeJsonStringify, type LogFormat, type Logger } from './logger'
export { MetricsCollector, type MetricsSnapshot, type TimerSummary } from './metrics'
export {
  CreateGenerationSchema,
  GenerationListViewSchema,
  ListGenerationsSchema,
  GetGenerationSchema,
  SetGenerationLibraryStateSchema,
  UserIdQuerySchema,
  ModelParameterSchema,
  ProviderResultSchema,
  ApiResponseSchema,
  validateInput,
  safeValidate,
  type CreateGenerationInput,
  type GenerationListView,
  type ListGenerationsInput,
  type GetGenerationInput,
  type SetGenerationLibraryStateInput,
  type UserIdQuery,
  type ModelParameter,
  type ProviderResult,
  type ApiResponse,
} from './validation'

export {
  ErrorCode,
  BailianStudioError,
  ValidationError,
} from './errors'

export {
  CreateDirectorProjectSchema,
  CreateDirectorPhaseRunSchema,
  DirectorCharacterDraftSchema,
  DirectorCharacterSchema,
  DirectorCharactersResultSchema,
  DirectorLocationDraftSchema,
  DirectorLocationSchema,
  DirectorLocationsResultSchema,
  DirectorAnalysisResultSchema,
  AttachDirectorAssetSchema,
  DirectorAssetKindSchema,
  DirectorAssetOwnerTypeSchema,
  DirectorAssetResponseSchema,
  DirectorAssetSchema,
  DirectorShotDraftSchema,
  DirectorShotSchema,
  DirectorShotStatusSchema,
  DirectorStoryboardResultSchema,
  DirectorPhaseSchema,
  DirectorPhaseRunResponseSchema,
  DirectorPhaseRunSchema,
  DirectorPhaseRunStatusSchema,
  DirectorPhaseStatusSchema,
  DirectorProjectDetailSchema,
  DirectorProjectListResponseSchema,
  DirectorProjectProgressSchema,
  DirectorProjectResponseSchema,
  DirectorProjectStatusSchema,
  DirectorProjectSummarySchema,
  DirectorScriptVersionSchema,
  DirectorPhaseStateSchema,
  DIRECTOR_PHASE_LABELS,
  DIRECTOR_PHASES,
  DIRECTOR_PHASE_RUN_STATUS,
  DIRECTOR_PHASE_STATUS,
  DIRECTOR_PROJECT_STATUS,
  DIRECTOR_ASSET_KINDS,
  DIRECTOR_SHOT_STATUS,
  ListDirectorProjectsSchema,
  UpdateDirectorProjectSchema,
  type CreateDirectorProjectInput,
  type CreateDirectorPhaseRunInput,
  type DirectorAnalysisResult,
  type AttachDirectorAssetInput,
  type DirectorAsset,
  type DirectorAssetKind,
  type DirectorShot,
  type DirectorShotDraft,
  type DirectorStoryboardResult,
  type DirectorCharacterDraft,
  type DirectorCharacter,
  type DirectorCharactersResult,
  type DirectorLocationDraft,
  type DirectorLocation,
  type DirectorLocationsResult,
  type DirectorPhase,
  type DirectorPhaseRun,
  type DirectorPhaseRunStatus,
  type DirectorPhaseState,
  type DirectorPhaseStatus,
  type DirectorProjectDetail,
  type DirectorScriptVersion,
  type DirectorProjectListResult,
  type DirectorProjectProgress,
  type DirectorProjectStatus,
  type DirectorProjectSummary,
  type ListDirectorProjectsInput,
  type UpdateDirectorProjectInput,
} from './director'
